// Países con código de marcación. La bandera se calcula del ISO2 en el cliente.
window.COUNTRIES = [
  ["AF","Afghanistan","Afganistán","93"],
  ["AL","Albania","Albania","355"],
  ["DE","Germany","Alemania","49"],
  ["AD","Andorra","Andorra","376"],
  ["AO","Angola","Angola","244"],
  ["AI","Anguilla","Anguila","1264"],
  ["AG","Antigua and Barbuda","Antigua y Barbuda","1268"],
  ["SA","Saudi Arabia","Arabia Saudita","966"],
  ["DZ","Algeria","Argelia","213"],
  ["AR","Argentina","Argentina","54"],
  ["AM","Armenia","Armenia","374"],
  ["AW","Aruba","Aruba","297"],
  ["AU","Australia","Australia","61"],
  ["AT","Austria","Austria","43"],
  ["AZ","Azerbaijan","Azerbaiyán","994"],
  ["BS","Bahamas","Bahamas","1242"],
  ["BD","Bangladesh","Banglademesh","880"],
  ["BB","Barbados","Barbados","1246"],
  ["BH","Bahrain","Baréin","973"],
  ["BZ","Belize","Belice","501"],
  ["BJ","Benin","Benín","229"],
  ["BM","Bermuda","Bermudas","1441"],
  ["BY","Belarus","Bielorrusia","375"],
  ["BO","Bolivia","Bolivia","591"],
  ["BA","Bosnia and Herzegovina","Bosnia y Herzegovina","387"],
  ["BW","Botswana","Botsuana","267"],
  ["BR","Brazil","Brasil","55"],
  ["BN","Brunei","Brunéi","673"],
  ["BG","Bulgaria","Bulgaria","359"],
  ["BF","Burkina Faso","Burkina Faso","226"],
  ["BI","Burundi","Burundi","257"],
  ["BT","Bhutan","Bután","975"],
  ["BE","Belgium","Bélgica","32"],
  ["CV","Cape Verde","Cabo Verde","238"],
  ["KH","Cambodia","Camboya","855"],
  ["CM","Cameroon","Camerún","237"],
  ["CA","Canada","Canadá","1"],
  ["QA","Qatar","Catar","974"],
  ["TD","Chad","Chad","235"],
  ["CL","Chile","Chile","56"],
  ["CN","China","China","86"],
  ["CY","Cyprus","Chipre","357"],
  ["CO","Colombia","Colombia","57"],
  ["KM","Comoros","Comoras","269"],
  ["CG","Congo","Congo","242"],
  ["CD","DR Congo","Congo (RDC)","243"],
  ["KP","North Korea","Corea del Norte","850"],
  ["KR","South Korea","Corea del Sur","82"],
  ["CR","Costa Rica","Costa Rica","506"],
  ["CI","Ivory Coast","Costa de Marfil","225"],
  ["HR","Croatia","Croacia","385"],
  ["CU","Cuba","Cuba","53"],
  ["CW","Curaçao","Curazao","599"],
  ["DK","Denmark","Dinamarca","45"],
  ["DM","Dominica","Dominica","1767"],
  ["EC","Ecuador","Ecuador","593"],
  ["EG","Egypt","Egipto","20"],
  ["SV","El Salvador","El Salvador","503"],
  ["AE","United Arab Emirates","Emiratos Árabes Unidos","971"],
  ["ER","Eritrea","Eritrea","291"],
  ["SK","Slovakia","Eslovaquia","421"],
  ["SI","Slovenia","Eslovenia","386"],
  ["ES","Spain","España","34"],
  ["US","United States","Estados Unidos","1"],
  ["EE","Estonia","Estonia","372"],
  ["ET","Ethiopia","Etiopía","251"],
  ["PH","Philippines","Filipinas","63"],
  ["FI","Finland","Finlandia","358"],
  ["FJ","Fiji","Fiyi","679"],
  ["FR","France","Francia","33"],
  ["GA","Gabon","Gabón","241"],
  ["GM","Gambia","Gambia","220"],
  ["GE","Georgia","Georgia","995"],
  ["GH","Ghana","Ghana","233"],
  ["GI","Gibraltar","Gibraltar","350"],
  ["GD","Grenada","Granada","1473"],
  ["GR","Greece","Grecia","30"],
  ["GL","Greenland","Groenlandia","299"],
  ["GP","Guadeloupe","Guadalupe","590"],
  ["GU","Guam","Guam","1671"],
  ["GT","Guatemala","Guatemala","502"],
  ["GF","French Guiana","Guayana Francesa","594"],
  ["GN","Guinea","Guinea","224"],
  ["GQ","Equatorial Guinea","Guinea Ecuatorial","240"],
  ["GW","Guinea-Bissau","Guinea-Bisáu","245"],
  ["GY","Guyana","Guyana","592"],
  ["HT","Haiti","Haití","509"],
  ["HN","Honduras","Honduras","504"],
  ["HK","Hong Kong","Hong Kong","852"],
  ["HU","Hungary","Hungría","36"],
  ["IN","India","India","91"],
  ["ID","Indonesia","Indonesia","62"],
  ["IQ","Iraq","Irak","964"],
  ["IE","Ireland","Irlanda","353"],
  ["IR","Iran","Irán","98"],
  ["IS","Iceland","Islandia","354"],
  ["KY","Cayman Islands","Islas Caimán","1345"],
  ["IL","Israel","Israel","972"],
  ["IT","Italy","Italia","39"],
  ["JM","Jamaica","Jamaica","1876"],
  ["JP","Japan","Japón","81"],
  ["JO","Jordan","Jordania","962"],
  ["KZ","Kazakhstan","Kazajistán","7"],
  ["KE","Kenya","Kenia","254"],
  ["KG","Kyrgyzstan","Kirguistán","996"],
  ["KI","Kiribati","Kiribati","686"],
  ["KW","Kuwait","Kuwait","965"],
  ["LA","Laos","Laos","856"],
  ["LS","Lesotho","Lesoto","266"],
  ["LV","Latvia","Letonia","371"],
  ["LR","Liberia","Liberia","231"],
  ["LY","Libya","Libia","218"],
  ["LI","Liechtenstein","Liechtenstein","423"],
  ["LT","Lithuania","Lituania","370"],
  ["LU","Luxembourg","Luxemburgo","352"],
  ["LB","Lebanon","Líbano","961"],
  ["MO","Macao","Macao","853"],
  ["MK","North Macedonia","Macedonia del Norte","389"],
  ["MG","Madagascar","Madagascar","261"],
  ["MY","Malaysia","Malasia","60"],
  ["MW","Malawi","Malaui","265"],
  ["MV","Maldives","Maldivas","960"],
  ["MT","Malta","Malta","356"],
  ["ML","Mali","Malí","223"],
  ["MA","Morocco","Marruecos","212"],
  ["MU","Mauritius","Mauricio","230"],
  ["MR","Mauritania","Mauritania","222"],
  ["FM","Micronesia","Micronesia","691"],
  ["MD","Moldova","Moldavia","373"],
  ["MN","Mongolia","Mongolia","976"],
  ["ME","Montenegro","Montenegro","382"],
  ["MZ","Mozambique","Mozambique","258"],
  ["MM","Myanmar","Myanmar","95"],
  ["MX","Mexico","México","52"],
  ["MC","Monaco","Mónaco","377"],
  ["NA","Namibia","Namibia","264"],
  ["NR","Nauru","Nauru","674"],
  ["NP","Nepal","Nepal","977"],
  ["NI","Nicaragua","Nicaragua","505"],
  ["NG","Nigeria","Nigeria","234"],
  ["NO","Norway","Noruega","47"],
  ["NC","New Caledonia","Nueva Caledonia","687"],
  ["NZ","New Zealand","Nueva Zelanda","64"],
  ["NE","Niger","Níger","227"],
  ["OM","Oman","Omán","968"],
  ["PK","Pakistan","Pakistán","92"],
  ["PW","Palau","Palaos","680"],
  ["PS","Palestine","Palestina","970"],
  ["PA","Panama","Panamá","507"],
  ["PG","Papua New Guinea","Papúa Nueva Guinea","675"],
  ["PY","Paraguay","Paraguay","595"],
  ["NL","Netherlands","Países Bajos","31"],
  ["PE","Peru","Perú","51"],
  ["PF","French Polynesia","Polinesia Francesa","689"],
  ["PL","Poland","Polonia","48"],
  ["PT","Portugal","Portugal","351"],
  ["PR","Puerto Rico","Puerto Rico","1787"],
  ["GB","United Kingdom","Reino Unido","44"],
  ["CF","Central African Republic","República Centroafricana","236"],
  ["CZ","Czech Republic","República Checa","420"],
  ["DO","Dominican Republic","República Dominicana","1809"],
  ["RW","Rwanda","Ruanda","250"],
  ["RO","Romania","Rumania","40"],
  ["RU","Russia","Rusia","7"],
  ["WS","Samoa","Samoa","685"],
  ["KN","Saint Kitts and Nevis","San Cristóbal y Nieves","1869"],
  ["SM","San Marino","San Marino","378"],
  ["VC","Saint Vincent","San Vicente y las Granadinas","1784"],
  ["LC","Saint Lucia","Santa Lucía","1758"],
  ["ST","Sao Tome and Principe","Santo Tomé y Príncipe","239"],
  ["SN","Senegal","Senegal","221"],
  ["RS","Serbia","Serbia","381"],
  ["SC","Seychelles","Seychelles","248"],
  ["SL","Sierra Leone","Sierra Leona","232"],
  ["SG","Singapore","Singapur","65"],
  ["SY","Syria","Siria","963"],
  ["SO","Somalia","Somalia","252"],
  ["LK","Sri Lanka","Sri Lanka","94"],
  ["ZA","South Africa","Sudáfrica","27"],
  ["SD","Sudan","Sudán","249"],
  ["SS","South Sudan","Sudán del Sur","211"],
  ["SE","Sweden","Suecia","46"],
  ["CH","Switzerland","Suiza","41"],
  ["SR","Suriname","Surinam","597"],
  ["TH","Thailand","Tailandia","66"],
  ["TW","Taiwan","Taiwán","886"],
  ["TZ","Tanzania","Tanzania","255"],
  ["TJ","Tajikistan","Tayikistán","992"],
  ["TL","Timor-Leste","Timor Oriental","670"],
  ["TG","Togo","Togo","228"],
  ["TO","Tonga","Tonga","676"],
  ["TT","Trinidad and Tobago","Trinidad y Tobago","1868"],
  ["TM","Turkmenistan","Turkmenistán","993"],
  ["TR","Turkey","Turquía","90"],
  ["TV","Tuvalu","Tuvalu","688"],
  ["TN","Tunisia","Túnez","216"],
  ["UA","Ukraine","Ucrania","380"],
  ["UG","Uganda","Uganda","256"],
  ["UY","Uruguay","Uruguay","598"],
  ["UZ","Uzbekistan","Uzbekistán","998"],
  ["VU","Vanuatu","Vanuatu","678"],
  ["VE","Venezuela","Venezuela","58"],
  ["VN","Vietnam","Vietnam","84"],
  ["YE","Yemen","Yemen","967"],
  ["DJ","Djibouti","Yibuti","253"],
  ["ZM","Zambia","Zambia","260"],
  ["ZW","Zimbabwe","Zimbabue","263"]
];
